%% ficheiro de desenvolvimento e teste do Bloom Filter

%teste (links que pertencem)
% test_links = {'proudemocrat.com';
%     'fort-russ.com';
%     'prisonplanet.com';
%     'truthfeed.com';
%     'themindunleashed.com';
%     'usuncut.com';
%     'newstarget.com';
%     'counterpunch.org';
%     'jewsnews.co.il';
%     'educateinspirechange.org';
%     'clickhole.com';
%     'newcenturytimes.com';
%     'opednews.com';
%     'defenddemocracy.press';
%     'voltairenet.org';
%     'whatreallyhappened.com';
%     'winningdemocrats.com';
%     'other98.com';
%     'southfront.org';
%     'barenakedislam.com';
%     'dailywire.com';
%     'americasfreedomfighters.com';
%     'presidentialvoting2016.com';
%     'thesleuthjournal.com';
%     'nakedcapitalism.com';
%     'rumormillnews.com';
%     'greanvillepost.com';
%     'ncscooper.com';
%     'indiaarising.com';
%     'thelastlineofdefense.org';
%     'moonofalabama.org';
%     'prepperwebsite.com';
%     'allnewspipeline.com';
%     'corbettreport.com';
%     'blackagendareport.com';
%     'ihavethetruth.com';
%     'therundownlive.com';
%     'abeldanger.net';
%     'trueactivist.com';
%     'usatwentyfour.com';
%     'nowtheendbegins.com';
%     'intrepidreport.com';
%     'fellowshipoftheminds.com';
%     'veteransnewsnow.com';
%     'breitbart.com';
%     'conservativetribune.com';
%     'thefederalistpapers.org';
%     'unz.com';
%     'eutimes.net';
%     'libertyblitzkrieg.com';
%     'madworldnews.com';
%     'mediamass.net';
%     'investmentresearchdynamics.com';
%     'veteranstoday.com';
%     'regated.com';
%     'sgtreport.com';
%     'usapoliticsnow.com';
%     'nutritionfacts.org';
%     'worldtruth.tv';
%     'dcclothesline.com';
%     'in5d.com';
%     'fromthetrenchesworldreport.com';
%     'pravdareport.com';
%     'rt.com';
%     'therussophile.org';
%     'truthbroadcastnetwork.com';
%     'strategic-culture.org';
%     'ahtribune.com';
%     '100percentfedup.com';
%     'thecontroversialfiles.net';
%     'der-postillon.com';
%     'truthfrequencyradio.com';
%     'thedailywtf.com';
%     'elmundotoday.com';
%     'orientalreview.org';
%     'survivopedia.com';
%     'journal-neo.org';
%     'redflagnews.com';
%     'drudgereport.com';
%     'consortiumnews.com';
%     'presstv.com';
%     'libertyunyielding.com';
%     'thefreethoughtproject.com';
%     'coasttocoastam.com';
%     'dennismichaellynch.com';
%     'hangthebankers.com';
%     'yournewswire.com';
%     'anonews.co';
%     'newsbiscuit.com';
%     'projectveritas.com';
%     'realfarmacy.com';
%     'shtfplan.com';
%     'libertynews.com';
%     'newsthump.com';
%     'truthdig.com';
%     'anonhq.com';
%     'sputniknews.com';
%     'frontpagemag.com';
%     'returnofkings.com';
% };

% teste (links que não pertencem)
test_links = {
    'tau.org';
    'lambda.online';
    'gamma.online';
    'omega.co';
    'iota.tv';
    'pi.co';
    'alpha.co';
    'eta.tv';
    'hyper.com';
    'theta.org';
    'rho.biz';
    'stellar.info';
    'vortex.co';
    'chi.org';
    'sigma.online';
    'kappa.net';
    'quantum.biz';
    'crystal.tv';
    'beta.co';
    'zeta.online';
    'nova.com';
    'matrix.net';
    'omega.tv';
    'upsilon.co';
    'phi.info';
    'delta.biz';
    'mu.org';
    'tau.tv';
    'xi.com';
    'theta.co';
    'neon.online';
    'stellar.net';
    'iota.biz';
    'nu.org';
    'hyper.info';
    'psi.co';
    'kappa.com';
    'rho.org';
    'alpha.net';
    'gamma.com';
    'sigma.co';
    'vortex.biz';
    'omega.biz';
    'lambda.org';
    'eta.co';
    'zeta.com';
    'crystal.net';
    'quantum.co';
    'delta.online';
    'phi.co';
    'matrix.org';
    'stellar.biz';
    'upsilon.online';
    'neon.info';
    'nova.tv';
    'xi.biz';
    'beta.online';
    'pi.biz';
    'tau.co';
    'theta.biz';
    'eta.net';
    'rho.biz';
    'lambda.co';
    'sigma.biz';
    'iota.org';
    'nu.biz';
    'chi.co';
    'zeta.biz';
    'alpha.biz';
    'psi.online';
    'mu.biz';
    'kappa.biz';
    'phi.org';
    'xi.co';
    'delta.org';
    'gamma.biz';
    'nova.biz';
    'vortex.info';
    'theta.online';
    'neon.co';
    'stellar.org';
    'upsilon.biz';
    'quantum.biz';
    'eta.biz';
    'omega.info';
    'beta.biz';
    'lambda.biz';
    'sigma.info';
    'crystal.co';
    'phi.net';
    'rho.co';
    'nu.net';
    'stellar.co';
    'matrix.biz';
    'psi.biz';
    'theta.tv';
    'alpha.co';
    'neon.biz';
    'tau.org';
    'kappa.org';
    'xi.tv';
    'zeta.net';
    'gamma.co';
    'delta.co';
    'iota.net';
    'omega.net';
    'mu.co';
    'beta.net';
    'chi.net';
    'lambda.online';
    'nova.org';
    'quantum.info';
    'stellar.tv';
    'vortex.tv';
    'upsilon.net';
    'rho.org';
    'phi.biz';
    'zeta.org';
    'psi.info';
    'crystal.biz';
    'omega.biz';
    'alpha.info';
    'theta.net';
    'lambda.info';
    'neon.org';
    'nova.net';
    'sigma.org';
    'iota.online';
    'stellar.co';
    'quantum.co';
    'tau.net';
    'mu.net';
    'vortex.net';
    'rho.info';
    'xi.net';
    'delta.tv';
    'upsilon.org';
    'phi.tv';
    'nu.org';
    'beta.biz';
    'gamma.org';
    'alpha.tv';
    'chi.org';
    'eta.info';
    'lambda.net';
    'tau.online';
    'theta.org';
    'zeta.tv';
    'iota.biz';
    'psi.biz';
    'omega.online';
    'mu.online';
    'rho.co';
    'neon.co';
    'xi.online';
    'kappa.biz';
    'phi.online';
    'stellar.org';
    'upsilon.info';
    'delta.biz';
    'nova.biz';
    'crystal.tv';
    'gamma.biz';
    'lambda.biz';
    'vortex.co';
    'zeta.biz';
    'sigma.biz';
    'theta.biz';
    'rho.biz';
    'neon.biz';
    'alpha.biz';
    'beta.biz';
    'mu.biz';
    'tau.biz';
    'nu.biz';
    'xi.biz';
    'kappa.biz';
    'psi.biz';
    'phi.biz';
    'stellar.biz';
    'nova.biz';
    'lambda.biz';
    'sigma.biz';
    'upsilon.biz';
    'vortex.biz';
    'zeta.biz';
    'tau.org';
    'lambda.online';
    'gamma.online';
    'omega.co';
    'iota.tv';
    'pi.co';
    'alpha.co';
    'eta.tv';
    'hyper.com';
    'theta.org';
    'rho.biz';
    'stellar.info';
    'vortex.co';
    'chi.org';
    'sigma.online';
    'kappa.net';
    'quantum.biz';
    'crystal.tv';
    'beta.co';
    'zeta.online';
    'nova.com';
    'matrix.net';
    'omega.tv';
    'upsilon.co';
    'phi.info';
    'delta.biz';
    'mu.org';
    'tau.tv';
    'xi.com';
    'theta.co';
    'neon.online';
    'stellar.net';
    'iota.biz';
    'nu.org';
    'hyper.info';
    'psi.co';
    'kappa.com';
    'rho.org';
    'alpha.net';
    'gamma.com';
    'sigma.co';
    'vortex.biz';
    'omega.biz';
    'lambda.org';
    'eta.co';
    'zeta.com';
    'crystal.net';
    'quantum.co';
    'delta.online';
    'phi.co';
    'matrix.org';
    'stellar.biz';
    'upsilon.online';
    'neon.info';
    'nova.tv';
    'xi.biz';
    'beta.online';
    'pi.biz';
    'tau.co';
    'theta.biz';
    'eta.net';
    'rho.biz';
    'lambda.co';
    'sigma.biz';
    'iota.org';
    'nu.biz';
    'chi.co';
    'zeta.biz';
    'alpha.biz';
    'psi.online';
    'mu.biz';
    'kappa.biz';
    'phi.org';
    'xi.co';
    'delta.org';
    'gamma.biz';
    'nova.biz';
    'vortex.info';
    'theta.online';
    'neon.co';
    'stellar.org';
    'upsilon.biz';
    'quantum.biz';
    'eta.biz';
    'omega.info';
    'beta.biz';
    'lambda.biz';
    'sigma.info';
    'crystal.co';
    'phi.net';
    'rho.co';
    'nu.net';
    'stellar.co';
    'matrix.biz';
    'psi.biz';
    'theta.tv';
    'alpha.co';
    'neon.biz';
    'tau.org';
    'kappa.org';
    'xi.tv';
    'zeta.net';
    'orbitalsite.com';
    'fusiondata.net';
    'protonverse.org';
    'quarkinfo.biz';
    'stardustmedia.co';
    'gravitasphere.tv';
    'lightstream.info';
    'darkmatterhub.org';
    'plasmagrid.biz';
    'electronline.co';
    'neutrinozone.net';
    'galacticpulse.com';
    'astraverse.info';
    'cosmowave.biz';
    'timewarp.net';
    'quantapoint.org';
    'virtualscope.com';
    'nanowire.biz';
    'exoplanetary.co';
    'stellarforce.tv';
    'pulsarcore.com';
    'hyperspacelab.info';
    'spatialweb.net';
    'cosmichub.biz';
    'blackholemedia.org';
    'singularitywave.co';
    'eclipsematrix.com';
    'quantumnova.info';
    'orbitalhub.net';
    'xenoverse.biz';
    'nebulargrid.org';
    'galaxyforge.tv';
    'starrypath.co';
    'lightforce.net';
    'protoncore.com';
    'celestialgrid.info';
    'cosmicwave.biz';
    'lunarzone.net';
    'solarflare.org';
    'starmapdata.co';
    'cosmoworks.biz';
    'intergalacticnet.com';
    'astrobeam.org';
    'stardustportal.net';
    'gravwave.biz';
    'cosmosync.co';
    'luminverse.com';
    'stellargrid.info';
    'nebularstorm.net';
    'nanoflux.biz';
    'lunarforge.org';
    'darkstream.biz';
    'timeverse.co';
    'ionospheredata.com';
    'quantashift.org';
    'ethercore.net';
    'protonstream.biz';
    'wavegrid.info';
    'starline.org';
    'orbitpulse.com';
    'fusioncore.net';
    'astroforge.biz';
    'novaorbit.co';
    'neutrinolink.tv';
    'cosmicpulse.info';
    'galaxyline.biz';
    'xenopoint.net';
    'hypernova.org';
    'gravitashift.co';
    'quasarbeam.com';
    'lightgrid.info';
    'spacestream.net';
    'supernova.biz';
    'galacticgrid.org';
    'stellarwarp.co';
    'darkgrid.com';
    'nebulaportal.info';
    'quantabeam.net';
    'starpulse.biz';
    'cosmosync.org';
    'astroline.co';
    'galaxyweb.com';
    'fusionstorm.biz';
    'orbitgrid.info';
    'lunarhub.net';
    'blackholenet.org';
    'exostarwave.com';
    'gravitacore.biz';
    'stellarline.co';
    'starworks.info';
    'novaweb.net';
    'cosmicpoint.biz';
    'stardustline.org';
    'nebularhub.co';
    'quantaverse.com';
    'waveforge.biz';
    'astrohub.net';
    'ionostream.org';
    'celestialwarp.co';
    'hyperstream.net';
    'protonzone.biz';
    'darkzone.org';
    'lunarpath.co';
    'lightmatrix.com';
    'neutrinoscope.info';
    'quantumnode.net';
    'galacticstorm.biz';
    'astroverse.org';
    'superwarp.co';
    'protongrid.info';
    'singularityline.com';
    'orbitalsync.biz';
    'gravitaworks.co';
    'cosmichorizon.net';
    'starpulse.org';
    'stellarhorizon.biz';
    'fusionline.co';
    'nebulaverse.info';
    'astrostorm.net';
    'hypermatrix.biz';
    'darkpulse.co';
    'quantaworks.com';
    'galaxybeam.net';
    'cosmowarp.biz';
    'lightnet.org';
    'stellarforge.co';
    'darkforce.info';
    'spatialpulse.biz';
    'luminpath.org';
    'plasmamatrix.net';
    'stardustgrid.biz';
    'novaion.co';
    'blackholegrid.com';
    'nanostream.net';
    'protonhub.biz';
    'astroline.org';
    'nebulacore.co';
    'waveforce.info';
    'quasarforge.net';
    'darkweb.biz';
    'quantabeam.co';
    'galacticforge.info';
    'astrowarp.org';
    'fusionweb.biz';
    'orbitline.co';
    'stellarstorm.com';
    'superflare.net';
    'hyperpath.biz';
    'lightstorm.org';
    'gravitaline.net';
    'cosmoforge.biz';
    'novaionline.co';
    'celestialpulse.info';
    'astroflare.biz';
    'quasarhub.net';
    'ionstorm.org';
    'protonpulse.co';
    'galaxyzone.com';
    'lunarforce.info';
    'stardustworks.net';
    'fusionpulse.biz';
    'nebulaline.co';
    'stellarweb.org';
    'gravitaforce.net';
    'astrocore.biz';
    'spatialforge.com';
    'lightcore.net';
    'singularityhub.biz';
    'cosmiczone.org';
    'novaforge.biz';
    'darkwarp.co';
    'astrogrid.info';
    'neutrinohub.biz';
    'stellarline.net';
    'orbitmatrix.org';
    'galacticpath.co';
    'hyperforce.com';
    'stellarion.net';
    'plasmabeam.biz';
    'darknova.org';
    'lightzone.co';
    'celestialcore.info';
    'novaweb.biz';
    'starhorizon.co';
    'nebularpulse.info';
    'protonline.biz';
    'ionpath.org';
};



positives = 0; % nº de positivos
negatives = 0; % nº de negativos

for l = 1:length(test_links) % for de teste
test_link = test_links{l}; % link em teste


%% ------------------------------------------------------------------------
% verificação inicial usando Bloom Filter

linkscsv = 'bf_data_fake.csv'; % ficheiro CSV com os links

data = readtable(linkscsv); % links processados
urls=unique(data.site_url);
clear data

% parâmetros iniciais
m = length(urls);
p = 0.001; % probabilidade de falsos positivos desejada (1%)
n = ceil(- (m * log(p))/(log(2))^2); % tamanho do vetor 
k = ceil((n/m)*log(2)); % nº de funções de dispersão

% inicialização do bloom filter
bloom_filter = initialize(n);


% inserção de elementos no bloom filter
for i = 1:height(urls)
    bloom_filter = insert(urls{i}, bloom_filter, k);
    % disp(data.site_url{i}); % mostrar o que foi inserido
end

% verificar se um link fornecido pertence à base de dados
ismember = verify(bloom_filter, test_link, k);

% -------------------------------------------------------------------------
%% testar os nº de falsos positivos
if ismember == 1
    positives = positives + 1;
    fprintf('A notícia do site "%s" pode ser fake news!\n', test_link)
else
    negatives = negatives + 1;
    fprintf('A notícia do site "%s" não está registada como possível fake news!\n', test_link)
end


end % end do for de teste
fprintf('Positives: %d\n', positives)
fprintf('Negatives: %d\n', negatives)
fprintf("end of test")